"""Initial schema

Revision ID: 2c1dd196fdd7
Revises: 
Create Date: 2025-11-14 14:23:18.369343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1dd196fdd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bond_types',
    sa.Column('bond_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bond_name', sa.String(length=100), nullable=False),
    sa.Column('maturity_period_years', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('bond_type_id')
    )
    op.create_index(op.f('ix_bond_types_bond_type_id'), 'bond_types', ['bond_type_id'], unique=False)
    op.create_index(op.f('ix_bond_types_maturity_period_years'), 'bond_types', ['maturity_period_years'], unique=False)
    op.create_table('fee_structure',
    sa.Column('fee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fee_name', sa.String(length=100), nullable=False),
    sa.Column('fee_type', sa.Enum('PERCENTAGE', 'FIXED', name='feetype'), nullable=False),
    sa.Column('fee_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('applies_to', sa.Enum('COUPON', 'DISCOUNT', 'REDEMPTION', 'ALL', name='appliesto'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('fee_id')
    )
    op.create_index(op.f('ix_fee_structure_fee_id'), 'fee_structure', ['fee_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('user_role', sa.Enum('ADMIN', 'TREASURER', 'MEMBER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_user_role'), 'users', ['user_role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('action_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_table_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_index('idx_user_timestamp', 'audit_logs', ['user_id', 'action_timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_timestamp'), 'audit_logs', ['action_timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_log_id'), 'audit_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('bond_purchases',
    sa.Column('purchase_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bond_type_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_month', sa.Date(), nullable=False),
    sa.Column('bond_shares', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('coop_discount_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_discount_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('purchase_status', sa.Enum('ACTIVE', 'MATURED', 'REDEEMED', 'CANCELLED', name='purchasestatus'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bond_type_id'], ['bond_types.bond_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('purchase_id'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_index(op.f('ix_bond_purchases_maturity_date'), 'bond_purchases', ['maturity_date'], unique=False)
    op.create_index(op.f('ix_bond_purchases_purchase_date'), 'bond_purchases', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_bond_purchases_purchase_id'), 'bond_purchases', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_bond_purchases_user_id'), 'bond_purchases', ['user_id'], unique=False)
    op.create_table('interest_rates',
    sa.Column('rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bond_type_id', sa.Integer(), nullable=False),
    sa.Column('effective_month', sa.Date(), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('daily_coupon_rate', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bond_type_id'], ['bond_types.bond_type_id'], ),
    sa.ForeignKeyConstraint(['entered_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rate_id')
    )
    op.create_index(op.f('ix_interest_rates_effective_month'), 'interest_rates', ['effective_month'], unique=False)
    op.create_index(op.f('ix_interest_rates_rate_id'), 'interest_rates', ['rate_id'], unique=False)
    op.create_table('member_balances',
    sa.Column('balance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bond_type_id', sa.Integer(), nullable=False),
    sa.Column('balance_date', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('purchases_month', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payments_received', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_bond_shares', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_face_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('percentage_share', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bond_type_id'], ['bond_types.bond_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('balance_id'),
    sa.UniqueConstraint('user_id', 'bond_type_id', 'balance_date', name='uk_user_bond_date')
    )
    op.create_index('idx_user_date', 'member_balances', ['user_id', 'balance_date'], unique=False)
    op.create_index(op.f('ix_member_balances_balance_date'), 'member_balances', ['balance_date'], unique=False)
    op.create_index(op.f('ix_member_balances_balance_id'), 'member_balances', ['balance_id'], unique=False)
    op.create_index(op.f('ix_member_balances_user_id'), 'member_balances', ['user_id'], unique=False)
    op.create_table('monthly_summaries',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary_month', sa.Date(), nullable=False),
    sa.Column('total_bond_shares', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_face_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_purchases', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_gross_coupons', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_withholding_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_boz_fees', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_coop_fees', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_net_payments', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_cooperative_income', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('active_members_count', sa.Integer(), nullable=False),
    sa.Column('new_purchases_count', sa.Integer(), nullable=False),
    sa.Column('matured_bonds_count', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index(op.f('ix_monthly_summaries_summary_id'), 'monthly_summaries', ['summary_id'], unique=False)
    op.create_index(op.f('ix_monthly_summaries_summary_month'), 'monthly_summaries', ['summary_month'], unique=True)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('PAYMENT_DUE', 'PAYMENT_PROCESSED', 'MATURITY_APPROACHING', 'RATE_UPDATE', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('idx_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('setting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=False),
    sa.Column('setting_type', sa.Enum('STRING', 'NUMBER', 'BOOLEAN', 'JSON', name='settingtype'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('setting_id')
    )
    op.create_index(op.f('ix_system_settings_category'), 'system_settings', ['category'], unique=False)
    op.create_index(op.f('ix_system_settings_setting_id'), 'system_settings', ['setting_id'], unique=False)
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)
    op.create_table('coupon_payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('SEMI_ANNUAL', 'MATURITY', 'EARLY_REDEMPTION', name='paymenttype'), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_period_start', sa.Date(), nullable=False),
    sa.Column('payment_period_end', sa.Date(), nullable=False),
    sa.Column('calendar_days', sa.Integer(), nullable=False),
    sa.Column('gross_coupon_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('withholding_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('boz_fees', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('coop_fees', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_payment_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PROCESSED', 'PAID', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('payment_reference', sa.String(length=50), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['processed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['bond_purchases.purchase_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_index(op.f('ix_coupon_payments_payment_date'), 'coupon_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_coupon_payments_payment_id'), 'coupon_payments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_coupon_payments_payment_status'), 'coupon_payments', ['payment_status'], unique=False)
    op.create_index(op.f('ix_coupon_payments_user_id'), 'coupon_payments', ['user_id'], unique=False)
    op.create_table('payment_vouchers',
    sa.Column('voucher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('voucher_type', sa.Enum('SEMI_ANNUAL', 'MATURITY', 'EARLY_REDEMPTION', name='paymenttype'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('voucher_status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'CANCELLED', name='voucherstatus'), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['coupon_payments.payment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('voucher_id')
    )
    op.create_index(op.f('ix_payment_vouchers_voucher_id'), 'payment_vouchers', ['voucher_id'], unique=False)
    op.create_index(op.f('ix_payment_vouchers_voucher_number'), 'payment_vouchers', ['voucher_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_vouchers_voucher_number'), table_name='payment_vouchers')
    op.drop_index(op.f('ix_payment_vouchers_voucher_id'), table_name='payment_vouchers')
    op.drop_table('payment_vouchers')
    op.drop_index(op.f('ix_coupon_payments_user_id'), table_name='coupon_payments')
    op.drop_index(op.f('ix_coupon_payments_payment_status'), table_name='coupon_payments')
    op.drop_index(op.f('ix_coupon_payments_payment_id'), table_name='coupon_payments')
    op.drop_index(op.f('ix_coupon_payments_payment_date'), table_name='coupon_payments')
    op.drop_table('coupon_payments')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_setting_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_category'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index('idx_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_monthly_summaries_summary_month'), table_name='monthly_summaries')
    op.drop_index(op.f('ix_monthly_summaries_summary_id'), table_name='monthly_summaries')
    op.drop_table('monthly_summaries')
    op.drop_index(op.f('ix_member_balances_user_id'), table_name='member_balances')
    op.drop_index(op.f('ix_member_balances_balance_id'), table_name='member_balances')
    op.drop_index(op.f('ix_member_balances_balance_date'), table_name='member_balances')
    op.drop_index('idx_user_date', table_name='member_balances')
    op.drop_table('member_balances')
    op.drop_index(op.f('ix_interest_rates_rate_id'), table_name='interest_rates')
    op.drop_index(op.f('ix_interest_rates_effective_month'), table_name='interest_rates')
    op.drop_table('interest_rates')
    op.drop_index(op.f('ix_bond_purchases_user_id'), table_name='bond_purchases')
    op.drop_index(op.f('ix_bond_purchases_purchase_id'), table_name='bond_purchases')
    op.drop_index(op.f('ix_bond_purchases_purchase_date'), table_name='bond_purchases')
    op.drop_index(op.f('ix_bond_purchases_maturity_date'), table_name='bond_purchases')
    op.drop_table('bond_purchases')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_log_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_timestamp'), table_name='audit_logs')
    op.drop_index('idx_user_timestamp', table_name='audit_logs')
    op.drop_index('idx_table_record', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_role'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fee_structure_fee_id'), table_name='fee_structure')
    op.drop_table('fee_structure')
    op.drop_index(op.f('ix_bond_types_maturity_period_years'), table_name='bond_types')
    op.drop_index(op.f('ix_bond_types_bond_type_id'), table_name='bond_types')
    op.drop_table('bond_types')
    # ### end Alembic commands ###
